In [ ]:
aList = ["John", 33,"Toronto", True]
print(aList)


['John', 33, 'Toronto', True]


In [ ]:
from datetime import date
tanggal = date.today()
print(tanggal)
import datetime as vDate
tanggal = vDate.date.today()
mahasiswa = ["Keren Sandra Sudarta", "2024071031",  "Informatika", "DAA", tanggal, "Universitas Pembangunan Jaya"]
print(mahasiswa)

2025-09-15
['Keren Sandra Sudarta', '2024071031', 'Informatika', 'DAA', datetime.date(2025, 9, 15), 'Universitas Pembangunan Jaya']


In [ ]:
print("NIM", mahasiswa[1])
print("Kampus", mahasiswa[5])

NIM 2024071031
Kampus Universitas Pembangunan Jaya


In [ ]:
from datetime import date
tanggal = date.today()
print(tanggal)

import datetime as vDate
hari = vDate.date.today()

tanggal = vDate.date.today()
print(hari)
print(tanggal)

mahasiswa = ["Keren Sandra Sudarta", "2024071031",  "Informatika", "DAA", tanggal, "Universitas Pembangunan Jaya"]
print(mahasiswa)


2025-09-15
2025-09-15
2025-09-15
['Keren Sandra Sudarta', '2024071031', 'Informatika', 'DAA', datetime.date(2025, 9, 15), 'Universitas Pembangunan Jaya']


In [ ]:
#nim saja
print("NIM", mahasiswa[1:2])

NIM ['2024071031']


In [ ]:
#prodi saja
print("Prodi", mahasiswa[2:3])

In [ ]:
#nim dan prodi
print("NIM & Prodi", mahasiswa[1:3])

NIM & Prodi ['2024071031', 'Informatika']


In [ ]:
#MK dan tanggal
print("MK & Tanggal berapa?", mahasiswa[3:5])

MK & Tanggal berapa? ['DAA', datetime.date(2025, 9, 15)]


In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_color']+= "Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'GreenPurple', 'refused_color': 'Red'}


In [ ]:
mahasiswa = ["Keren Sandra Sudarta", "2024071031",  "Informatika", "DAA", tanggal, "Universitas Pembangunan Jaya"]
print(mahasiswa[1]) #nim
print(mahasiswa[-1]) #universitas
print(mahasiswa[1:3]) #nim + prodi
for item in mahasiswa:
    print("UPJ, item")

2024071031
Universitas Pembangunan Jaya
['2024071031', 'Informatika']
UPJ, item
UPJ, item
UPJ, item
UPJ, item
UPJ, item
UPJ, item


In [ ]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))
print(nested_tuple[1][2])

600


In [ ]:
mhs = {
    "Nama" : "Keren Sandra Sudarta",
    "NIM" : "2024071031",
    "Prodi" : "Informatika",
    "Universitas" : "UPJ"
}
print(mhs["NIM"])
mhs["Prodi"] = "Informatika"


2024071031


In [ ]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [ ]:
yellow = {'dandelions', 'leaves', 'firehydrant'}
red = {'blood', 'red', 'firehydrant'}

print("Union of yellow and red:", yellow | red)
print("Intersection of yellow and red:", yellow & red)

Union of yellow and red: {'dandelions', 'leaves', 'firehydrant', 'red', 'blood'}
Intersection of yellow and red: {'firehydrant'}


In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])

In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
# Seleksi kolom
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
# Row selection
df.iloc[1:3,:]


id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [ ]:
import pandas as pd
mhs = pd.DataFrame({
    'No': [1, 2, 3],
    'Prodi': ['Informatika', 'Sistem Informasi', 'Teknik Sipil'],
    'Mahasiswa': [50, 55, 40],
    'Lakilaki': [30, 30, 30],
    'Perempuan': [20, 25, 10]})

In [ ]:
print("DataFrame mhs:")
print(mhs)

DataFrame mhs:
   No             Prodi  Mahasiswa  Lakilaki  Perempuan
0   1       Informatika         50        30         20
1   2  Sistem Informasi         55        30         25
2   3      Teknik Sipil         40        30         10


In [ ]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
])

print("Matrix Original:")
print(matrix)

Matrix Original:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [ ]:
matrix_transpose = matrix.T

print("Matrix Transpose:")
print(matrix_transpose)

Matrix Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
# Vektor Menggunakan ;ist phyton:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [ ]:
print(type(myVector))

<class 'list'>


In [ ]:
#Menggunakan array numpy:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [ ]:
print(type(myVector))

<class 'numpy.ndarray'>


In [2]:
# Stack
class Stack:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()

    def peek(self):
        return self.items[len(self.items)-1]

    def size(self):
        return len(self.items)

    def display(self):
        return self.items


In [3]:
# Contoh penggunaan Stack
stack = Stack()
print(f"Stack kosong? {stack.isEmpty()}")

Stack kosong? True


In [4]:
# Menambahkan elemen (push)
print("\nMenambahkan elemen ke stack:")
stack.push("A")
print(f"Push 'A': {stack.display()}")
stack.push("B")
print(f"Push 'B': {stack.display()}")
stack.push("C")
print(f"Push 'C': {stack.display()}")

print(f"\nUkuran stack: {stack.size()}")
print(f"Elemen teratas (peek): {stack.peek()}")


Menambahkan elemen ke stack:
Push 'A': ['A']
Push 'B': ['A', 'B']
Push 'C': ['A', 'B', 'C']

Ukuran stack: 3
Elemen teratas (peek): C


In [6]:
# Menghapus elemen (pop)
print("\nMenghapus elemen dari stack:")
print(f"Pop: {stack.pop()}, Stack sekarang: {stack.display()}")
print(f"Pop: {stack.pop()}, Stack sekarang: {stack.display()}")

print(f"Stack kosong? {stack.isEmpty()}")


Menghapus elemen dari stack:
Pop: C, Stack sekarang: ['A', 'B']
Pop: B, Stack sekarang: ['A']
Stack kosong? False


In [7]:
# Queue
class Queue(object):
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0, item)

    def dequeue(self):
        return self.items.pop()

    def size(self):
        return len(self.items)

    def display(self):
        return self.items

In [8]:
# Contoh penggunaan Queue
queue = Queue()
print(f"Queue kosong? {queue.isEmpty()}")

Queue kosong? True


In [9]:
# Menambahkan elemen (enqueue)
print("\nMenambahkan elemen ke queue:")
queue.enqueue("X")
print(f"Enqueue 'X': {queue.display()}")
queue.enqueue("Y")
print(f"Enqueue 'Y': {queue.display()}")
queue.enqueue("Z")
print(f"Enqueue 'Z': {queue.display()}")

print(f"\nUkuran queue: {queue.size()}")


Menambahkan elemen ke queue:
Enqueue 'X': ['X']
Enqueue 'Y': ['Y', 'X']
Enqueue 'Z': ['Z', 'Y', 'X']

Ukuran queue: 3


In [10]:
# Menghapus elemen (dequeue)
print("\nMenghapus elemen dari queue (FIFO):")
print(f"Dequeue: {queue.dequeue()}, Queue sekarang: {queue.display()}")
print(f"Dequeue: {queue.dequeue()}, Queue sekarang: {queue.display()}")

print(f"Queue kosong? {queue.isEmpty()}")


Menghapus elemen dari queue (FIFO):
Dequeue: X, Queue sekarang: ['Z', 'Y']
Dequeue: Y, Queue sekarang: ['Z']
Queue kosong? False


In [11]:
# Binary Tree
class TreeNode:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

class BinaryTree:
    def __init__(self):
        self.root = None

    def insert(self, data):
        if self.root is None:
            self.root = TreeNode(data)
        else:
            self._insert_recursive(self.root, data)

    def _insert_recursive(self, node, data):
        if data < node.data:
            if node.left is None:
                node.left = TreeNode(data)
            else:
                self._insert_recursive(node.left, data)
        else:
            if node.right is None:
                node.right = TreeNode(data)
            else:
                self._insert_recursive(node.right, data)

    def search(self, data):
        return self._search_recursive(self.root, data)

    def _search_recursive(self, node, data):
        if node is None:
            return False
        if node.data == data:
            return True
        elif data < node.data:
            return self._search_recursive(node.left, data)
        else:
            return self._search_recursive(node.right, data)

    def inorder_traversal(self):
        result = []
        self._inorder_recursive(self.root, result)
        return result

    def _inorder_recursive(self, node, result):
        if node:
            self._inorder_recursive(node.left, result)
            result.append(node.data)
            self._inorder_recursive(node.right, result)

    def preorder_traversal(self):
        result = []
        self._preorder_recursive(self.root, result)
        return result

    def _preorder_recursive(self, node, result):
        if node:
            result.append(node.data)
            self._preorder_recursive(node.left, result)
            self._preorder_recursive(node.right, result)

    def postorder_traversal(self):
        result = []
        self._postorder_recursive(self.root, result)
        return result

    def _postorder_recursive(self, node, result):
        if node:
            self._postorder_recursive(node.left, result)
            self._postorder_recursive(node.right, result)
            result.append(node.data)

    def display_tree(self):
        if self.root is None:
            print("Tree kosong")
            return
        self._display_recursive(self.root, 0)

    def _display_recursive(self, node, level):
        if node:
            self._display_recursive(node.right, level + 1)
            print("    " * level + str(node.data))
            self._display_recursive(node.left, level + 1)

In [12]:
# Contoh penggunaan Binary Search Tree
print("Membuat Binary Search Tree:")
bst = BinaryTree()

Membuat Binary Search Tree:


In [13]:
# Memasukkan data
data_list = [50, 30, 70, 20, 40, 60, 80]
print(f"Memasukkan data: {data_list}")

for data in data_list:
    bst.insert(data)

print("\nStruktur tree:")
bst.display_tree()

Memasukkan data: [50, 30, 70, 20, 40, 60, 80]

Struktur tree:
        80
    70
        60
50
        40
    30
        20


In [14]:
# Traversal
print(f"\nInorder traversal (terurut): {bst.inorder_traversal()}")
print(f"Preorder traversal: {bst.preorder_traversal()}")
print(f"Postorder traversal: {bst.postorder_traversal()}")


Inorder traversal (terurut): [20, 30, 40, 50, 60, 70, 80]
Preorder traversal: [50, 30, 20, 40, 70, 60, 80]
Postorder traversal: [20, 40, 30, 60, 80, 70, 50]


In [15]:
# Pencarian
print("\nMencari data dalam tree:")
search_values = [40, 25, 80]
for value in search_values:
    found = bst.search(value)
    print(f"Mencari {value}: {'Ditemukan' if found else 'Tidak ditemukan'}")



Mencari data dalam tree:
Mencari 40: Ditemukan
Mencari 25: Tidak ditemukan
Mencari 80: Ditemukan


In [17]:
# Binary Tree Khusus
print("1. Full Binary Tree - Setiap node memiliki 0 atau 2 anak")
full_tree = BinaryTree()
full_tree.root = TreeNode(1)
full_tree.root.left = TreeNode(2)
full_tree.root.right = TreeNode(3)
full_tree.root.left.left = TreeNode(4)
full_tree.root.left.right = TreeNode(5)

print("Full Binary Tree:")
full_tree.display_tree()

print("\n2. Perfect Binary Tree - Semua level penuh, semua daun pada level yang sama")
perfect_tree = BinaryTree()
perfect_tree.root = TreeNode(1)
perfect_tree.root.left = TreeNode(2)
perfect_tree.root.right = TreeNode(3)
perfect_tree.root.left.left = TreeNode(4)
perfect_tree.root.left.right = TreeNode(5)
perfect_tree.root.right.left = TreeNode(6)
perfect_tree.root.right.right = TreeNode(7)

print("Perfect Binary Tree:")
perfect_tree.display_tree()

print("\nSelesai! Semua implementasi berhasil dibuat.")

1. Full Binary Tree - Setiap node memiliki 0 atau 2 anak
Full Binary Tree:
    3
1
        5
    2
        4

2. Perfect Binary Tree - Semua level penuh, semua daun pada level yang sama
Perfect Binary Tree:
        7
    3
        6
1
        5
    2
        4

Selesai! Semua implementasi berhasil dibuat.
